[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = '#F63366'
backgroundColor = '#DEC9B2'
secondaryBackgroundColor = '#F0F2F6'
textColor = '#262730'
font = 'sans serif'
